### ISSUE TITLE
Borrow format from Learn-Travis for this Tutorial

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-circleci#1]
document the steps you go through to setup CircleCI for ART 
we like to have as many screenshots as possible e.g: https://github.com/dwyl/learn-travis

@des-des if you get time, please go for it!

**Comment by nelsonic** [comment]
Intro image? https://www.google.co.uk/search?tbm=isch&q=you+had+one+job+building

**Comment by des-des** [comment]
cool! assign me?

**Comment by des-des** [comment]
@nelsonic 
![image](https://cloud.githubusercontent.com/assets/12845233/12651864/4c3fc3b4-c5e0-11e5-97ea-e278144eb073.png)
Shall I fork it?

**Comment by nelsonic** [comment]
What...?! flipping Github permissions. let me check...

**Comment by nelsonic** [comment]
@des-des please refresh and try again. it was a _new_ repo so hadn't been added to the team...

**Comment by des-des** [comment]
:+1:

**Comment by nelsonic** [comment]
Tutorial updated for 2018. ✅ 
Thanks again @des-des ❤️
