### ISSUE TITLE
How to activate all of my repos?

### ISSUE THREAD

**Issue by tunnckoCore** [dwyl/learn-circleci#8]
Heya, just quick support. I believe someone here can answer faster than the support, don't why ;d But anyway.

When I logged to CircleCI today i seen one page that has all orgs and my account and all repos and one checkbox that can "activate" all repos. I just deselect all orgs and my repos, then just select a few repos from my account. I can't find that page now. I only can active repos one by one, but it is too much and too hard job to click on every single button of these ~300-350 repos. Not to mention the another 10+ orgs that i have access to.. ;d

![2017-03-28-15 05 25_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/24404005/07af0afc-13c8-11e7-8534-f39cdfb2c370.png)

As u see, there's a button for each repo, but when is clicked it makes a redirect, kind of like it is in appveyor, which is weird..

**Comment by tunnckoCore** [comment]
CircleCI is really fast and awesome, i'm just very angry and very tired of TravisCI. I'm considering that move from years... Finally I moved! yay!

edit: this [tweet](https://twitter.com/tunnckoCore/status/846660539694682112) was the peak of my anger to travis. All of my new builds (and future builds) failed, because some travis developer is sad and sleepy, no thanks!

**Comment by jruts** [comment]
@tunnckoCore it's awesome you feel this way, but please watch your language on these public repositories please.

**Comment by tunnckoCore** [comment]
Yea, but i just can't, i'm tired of Travis from years, and today i just explode.

**Comment by jruts** [comment]
@tunnckoCore I understand :) I have to deal with frustrations like this daily, but still, GitHub as a developer is part of your identity so be careful with what you say :)

Can I ask you to modify your message?

**Comment by nelsonic** [comment]
@tunnckoCore what _specifically_ do you dislike about Travis-CI? 😞 
(_there are few things we don't like on travis but on the whole it's really good to us... 
so I'm curious what has got you so frustrated... and I'm sure everyone `else` is too!_) 

Also, the _people_ from Travis-CI are _really_ nice ❤️ 
and they _listen_ when you make suggestions for improvements, 👂 
just share your thoughts with @joshk or https://twitter.com/travisci 👍

**Comment by tunnckoCore** [comment]
@jruts which part? Maybe `tired of freaking shit called TravisCI` ?

@nelsonic Specifically... I'm not anger for the first time. In most cases it is good, yea. But I really hate to adjust to some things. Yea, in most scenarios, it just works - go to travis, sync repos, click add repo, done.

In today's case, I just seen that for some reason the build step was changed, that causes `yarn` to be ran on node 0.10 and node 0.12 and exists with 1 code. More specifically, it is strange that `yarn` is called _after_ the `npm install` which not make any sense. I believe that some `if` condition is changed or removed in the `/home/travis/build.sh` (dont knwo what's that but it is in the log).

Before few days, everything was working with just skipping the yarn call on node < 4.

See the difference between this two builds - [before 5 days, on node 0.10](https://travis-ci.org/tunnckoCore/dush-router/jobs/214078482) and [today on node 0.10](https://travis-ci.org/tunnckoCore/dush-router/jobs/215871148) - I'm sure if I run the same commit from before 5 days, today will fail. No changes to the config, no failing tests (EVEN WINDOWS PASS), nothing. 

So it is clear that the problem is in the travis - some developer messed something, Yea it can be fixed, but I don't have the nerves and time to wait. I posted few angry tweets to Travis's twitter, sorry for the tone there, but... #ragequit.

Edit: Not to mention that CircleCI seems and feels a lot faster, in any way.

**Comment by jruts** [comment]
@tunnckoCore , exactly that xD
Btw, you should write a readme on how to arch-linux :p I am very interested.

**Comment by tunnckoCore** [comment]
> Btw, you should write a readme on how to arch-linux :p

@jruts yeaaa, totally! I'm trying from few months to write an article and make a few screencast to feel that ArchLinux i3 setup, it is just awesome and fast-fingers-oriented (keyboard oriented), I just need to learn vim and i'll be totally keyboard guru :D 

> exactly that xD

:+1:

**Comment by tunnckoCore** [comment]
@nelsonic btw, for same reasons I left Coveralls and moved to CodeCov. It is even more bad than Travis :D CodeCov just works, even not needed to visit their site, everything is automatic - in the moment I click on the badge which points to some repo that is just created, it is "activated" and in the moment that build finish it sends results - no devDeps, no nothing.

![2017-03-28-15 44 44_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/24405445/883376c2-13cd-11e7-91fa-abc2f4082cbf.png)

**Comment by tunnckoCore** [comment]
Btw.. how original... 

![2017-03-28-15 55 51_857x44_scrot](https://cloud.githubusercontent.com/assets/5038030/24405888/18e6ecf2-13cf-11e7-83f3-ccbc2b483f60.png)

There's a "unfollow all", but there's no "follow all" :D I though that if i unfollow all, then the button will be changed to "follow all", but nope.. ;/ still is "unfollow all" even there's no followed projects anymore :D Oookey.

I'm going to write an email.

**Comment by joshk** [comment]
Hi @nelsonic, thanks for the kind words and pinging me in here.

@tunnckoCore I'm sorry you feel this way about Travis. We do try our best to provide a great CI solution for all projects. Sometimes we don't get it right, but we listen to feedback, iterate, and improve.

You mention `some travis developer is sad and sleepy`, what happened in this instance? I'd love to learn what went wrong so we can see how we can improve our processes.

You also say `tired of freaking shit called TravisCI`, happy to hear of different naming suggestions 😄 

In all honesty, we can only improve as a product and service when we hear feedback. Tweet feedback is good, but it is sometimes laden with emotion which can make it harder for us to understand the issue. A friendly email explaining the problem and how it is affecting you and other developers helps us greatly.

We are a small-ish bootstrapped team trying to provide the Open Source community with a stable and reliable solution. We acknowledge and accept that we have things we can, and should, improve on. Every bit of help is appreciated and goes a long way. But that all said, if Travis isn't right for you and your team, we would love to hear your feedback so we can make the experience better for others.

Have an awesome day.

Josh

**Comment by nelsonic** [comment]
@olstenlarck did you figure out how to enable all of your repositories? 
(_would be good to get a conclusion so we can **close** this issue ... thanks!_)

**Comment by tunnckoCore** [comment]
Dont think so. Im doing it manually on each new repo.

**Comment by nelsonic** [comment]
Cool. it's _lame_ that it's _manual_, but at least you aren't creating more than one repo per _day_, hey? 😉

**Comment by tunnckoCore** [comment]
Meeeh. Some times more than one, but yea. The sad thing is that in both @tunnckoCore and @olstenlarck are tons of repos, and if i need to activate them manually one by one... Anyway. I'll get time to email them to ask and report here if get some response.
