### ISSUE TITLE
When is the service going to be functioning again?

### ISSUE THREAD

**Issue by Conorc1000** [dwyl/learn-circleci#9]
We are currently having lots of problems getting the service to work. Apparently due to a degraded service. 
![screen shot 2017-05-10 at 10 02 42](https://cloud.githubusercontent.com/assets/12072531/25891150/e174b960-3567-11e7-96d5-4d30a1ab18ea.png)

does anyone know when the service will be running normally again?

Thanks

**Comment by tunnckoCore** [comment]
It happens from time to time. It's normal i think.

**Comment by nelsonic** [comment]
@Conorc1000 I think CircleCI "2.0" is much more reliable. have you seen issues _recently_? 🤔

**Comment by Conorc1000** [comment]
Thanks for the replies, @nelsonic and @olstenlarck, im happy to close this.
